import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Trip } from '@/types';

export function generateTripPDF(trip: Trip) {
    const doc = new jsPDF();

    // -- Header --
    doc.setFillColor(39, 39, 42); // Zinc-800
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text(trip.title, 20, 20);

    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`${trip.days.length} Days in ${trip.destination}`, 20, 30);

    let yPos = 50;

    // -- Content per Day --
    trip.days.forEach((day, index) => {
        // Check for page break
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }

        // Day Header
        doc.setFillColor(240, 240, 240);
        doc.rect(14, yPos - 6, 182, 12, 'F');
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text(`Day ${day.day}: ${day.title}`, 20, yPos);
        yPos += 15;

        // Activities Table
        const tableBody = day.activities.map(act => [
            act.time,
            act.title,
            act.location.name
        ]);

        autoTable(doc, {
            startY: yPos,
            head: [['Time', 'Activity', 'Location']],
            body: tableBody,
            theme: 'grid',
            headStyles: { fillColor: [59, 130, 246] }, // Blue-500
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 25 },
                1: { cellWidth: 80 },
                2: { cellWidth: 'auto' }
            },
            margin: { left: 20, right: 20 }
        });

        // @ts-ignore
        yPos = doc.lastAutoTable.finalY + 15;
    });

    // -- Footer --
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by AI Trip Planner", 105, 290, { align: "center" });

    doc.save(`${trip.title.replace(/\s+/g, '_')}_Itinerary.pdf`);
}
